# Generated by Django 5.2.17 on 2026-09-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0003_alter_bloodrequest_blood_group'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='blood_request',
            field=models.ForeignKey(blank=True, help_text='Associated Blood Request if this donation fulfilled a specific request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood_requests.bloodrequest'),
        ),
    ]
