# Generated by Django 5.2.17 on 2026-09-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_latitude_user_longitude'),
        ('blood_requests', '0003_alter_bloodrequest_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Associated hospital facility entity for Hospital Staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='blood_requests.hospital'),
        ),
    ]
