# Generated by Django 5.2.17 on 2026-09-12 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Clinical or emergency justification for requesting donor contact.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Current consent status (PENDING, APPROVED, DECLINED).', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, help_text='Timestamp when the donor accepted or declined the request.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(help_text='Target donor whose contact details are requested.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='donors.donor')),
                ('requester', models.ForeignKey(help_text='User requesting access to donor contact details.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_donor_contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Contact Request',
                'verbose_name_plural': 'Donor Contact Requests',
                'db_table': 'donor_contact_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'donor', 'status'], name='donor_conta_request_6e8534_idx'), models.Index(fields=['donor', 'status'], name='donor_conta_donor_i_5425f8_idx')],
            },
        ),
    ]
