# Generated by Django 5.2.17 on 2026-09-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0003_alter_bloodrequest_blood_group'),
        ('donors', '0003_donorcontactrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcontactrequest',
            name='blood_request',
            field=models.ForeignKey(blank=True, help_text='Associated Blood Request if this contact request was raised for a specific request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_contact_requests', to='blood_requests.bloodrequest'),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='hospital_name',
            field=models.CharField(blank=True, default='', help_text='Name of the requesting hospital facility or department.', max_length=255),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A1+', 'A1+'), ('A1-', 'A1-'), ('A2+', 'A2+'), ('A2-', 'A2-'), ('A1B+', 'A1B+'), ('A1B-', 'A1B-'), ('A2B+', 'A2B+'), ('A2B-', 'A2B-')], default='', help_text='Requested ABO and Rh blood group for the patient/case.', max_length=5),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='urgency',
            field=models.CharField(blank=True, default='NORMAL', help_text='Urgency level (e.g. NORMAL, HIGH, CRITICAL).', max_length=20),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Purpose or clinical justification for requesting contact access.'),
        ),
        migrations.AddIndex(
            model_name='donorcontactrequest',
            index=models.Index(fields=['blood_request', 'donor'], name='donor_conta_blood_r_e49cb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='donorcontactrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('blood_request__isnull', False)), fields=('blood_request', 'donor'), name='unique_donor_contact_request_per_blood_request'),
        ),
    ]
