# Generated by Django 5.2.17 on 2026-09-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donorcontactrequest_blood_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcontactrequest',
            name='donation_outcome',
            field=models.CharField(choices=[('NOT_RECORDED', 'Not Recorded'), ('COMPLETED', 'Donation Completed'), ('DID_NOT_HAPPEN', 'Donation Did Not Happen')], default='NOT_RECORDED', help_text='Actual clinical outcome of the donation interaction recorded by the requesting Hospital Staff.', max_length=20),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='outcome_notes',
            field=models.TextField(blank=True, default='', help_text='Clinical or operational notes regarding the donation outcome.'),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='outcome_recorded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the donation outcome was recorded.', null=True),
        ),
        migrations.AddField(
            model_name='donorcontactrequest',
            name='outcome_recorded_by',
            field=models.ForeignKey(blank=True, help_text='Hospital Staff user who recorded the actual donation outcome.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donation_outcomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
