# Generated by Django 5.2.17 on 2026-09-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_blood_request'),
        ('donors', '0005_donorcontactrequest_donation_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcontactrequest',
            name='donation',
            field=models.OneToOneField(blank=True, help_text='Completed donation record associated with this contact request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_request', to='donations.donation'),
        ),
    ]
