# Generated by Django 5.2.17 on 2026-09-14 21:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donorcontactrequest_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth to verify age eligibility (18–65 years).', null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight in kilograms (minimum 50.0 kg required for donation).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
    ]
